version: '3'
services:
  db:
    image: postgres:latest
    container_name: db-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: warehouse-prod
    restart: always

  backend:
    build:
      dockerfile: Dockerfile
    container_name: warehouse-backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/warehouse-prod